_GPL.j(function(f,d,Ta,x,k,l,ia,t,Ua,ja,E,ob,pb,u,W,g,Va,ka,Wa,v,p,Mb,q,qb,rb){function da(a){a=ja.userAgent.match(ob(a+"[/ ](\\d+)","i"));return(a&&a[1])|0}function xa(a){var b=(a=a||g.event)&&a.type;b&&(a.cancelBubble=!0,a.preventDefault&&a.preventDefault(),a.returnValue=!1,a.stopImmediatePropagation&&a.stopImmediatePropagation(),a.stopPropagation&&a.stopPropagation());return!b}function ya(a,b,e){e=e||g;var X=!0;a&&f.each(a,function(d,c){return X=!!b.call(e,c,d,a)});return X}function sb(a){a&&"object"===
typeof a&&(a=f.extend.apply(f,arguments));return a}function tb(a,b,e,X){var d=[];ya(a,function(e,c){var f=b.call(this,e,c,a);(f!==W||X)&&d.push(f);return!0},e||g);return d}function z(a){var b={_:1E8*Math.random()|0},e="cdnstats-a.akamaihd.net";ya(arguments,function(a){"string"===typeof a?e=a:sb(b,"function"===typeof a?a(b):a);return!0});(new Image).src=d.proto+e+"/s.gif?"+tb(b,function(a,b){if(null!==a&&a!==W)return l(String(b))+"="+l(String(a))}).join("&")}function ub(a){var b=[];ya(a,function(a){0>
b.indexOf(a,void 0)&&b.push(a);return!0});return b}function J(){return new k/1E3|0}function za(a){var b=a&&String(a).match(/^([#.]?)([\w_-]+)/);return b?(a=b[2],a=za.v[a]||(za.v[a]=d.rs(8+(6*Math.random()|0))),b[1]+a):a}function R(){Aa(B,ka,R);vb(function(a,b,e){c=a;K||(K=!0,c!==Ba&&L&&(c+="&fo=1"),Ca(),Xa(),wb(),Ya(),e&&f('<link rel="dns-prefetch" href="//'+e+'">').appendTo(B.getElementsByTagName("head")[0]||M),Da=+new k,A(B,ka,Za,!1),$a=pb(function(){36E5<+new k-Da&&ea(!1)},5E3))})}function Za(a){Da=
+new k;K&&(h&&h.css("display","none"),x(Ea),Fa=a.target||a.srcElement,Ea=u(Ca,50))}function ea(a){K&&(x(Ea),h&&h.remove(),K=!1,Ta($a),xb(),Aa(B,ka,Za),c=void 0,Y=N="",Ga=!1,a||A(B,ka,R),u(R,1E3*Math.max(O,F)))}function A(a,b,e,d){if(g[Va]){d=la();try{return d.call(a,b,e,!0)}catch(c){a[Va](b,e,!0)}}else a.attachEvent("on"+b,e,!0)}function wb(){fa=!0;d.ah&&d.ah(G,S);f("*").add(g).each(function(a,b){ga(b)||A(b,G,S)});ab||(ab=!0,f("*").add(g).each(function(a,b){ga(b)||(A(b,"mousedown",T),A(b,"mouseup",
T),A(b,"click",T))}),d.ah&&(d.ah("mousedown",T),d.ah("mouseup",T),d.ah("click",T)));f("iframe").each(function(a,b){try{ga(b)||A(b.contentWindow,G,S)}catch(e){}})}function yb(){if(da("Chrome")){for(var a=0;a<ja.plugins.length;a++)if("Widevine Content Decryption Module"===ja.plugins[a].name)return!1;return!0}return!1}function Ca(){if(K){if(Fa)for(var a=Fa;a;){if(ga(a))return;a=a.parentNode}h&&!h.is(M.lastChild)&&(h.remove(),h=W);h||(h=f('<a style="z-index:999999999999999;padding:0;margin:0;cursor:default;opacity:0.01;position:fixed;top:0;left:0;background:transparent;width:100%;height:100%;">&nbsp;</a>'),
A(h[0],"mousedown",xa),A(h[0],"mouseup",xa),A(h[0],"click",S),h.appendTo(M));h.css("display","block");h.attr({target:bb(),href:c})}}function Xa(){K&&(!h||h.is(M.lastChild)&&"none"!==h.css("display")||Ca(),u(Xa,50))}function zb(a){Z.parentNode||(Ha=cb());f("#__modal,#__modal_container").remove();c!==t.href&&(x(db),function(a,b){db=u(function(){g.onbeforeunload=function(){};g.name=b;f("iframe").remove();t.href=a},300);ha=!0}(c,a),c=t.href,a="_blank");if(ja.userAgent.match(/\bEdge\/\d+/i))return Ha(c,
a);var b=Ha("","1749"===m?a:"_blank");b&&("_blank"!==a&&(b.name=a),.02>Math.random()?(a=""+c,-1<c.indexOf(P)&&c.match(/^https?:/i)&&(a="http://"+P+"/pclk?c="+l(N)+"&crl="+l(c)),b.location.href=a):b.location.href=c);return b}function bb(){var a="ld893_";N&&(a+="_"+l(N),Y&&(a+=","+Y),a+="_");return a+="_"+J()}function Ab(a){if(c!==Ba){a=a.target||a.srcElement;for(var b="";a;){aa||(aa=a.tagName);if("A"===a.tagName&&a.href&&a.protocol.toLowerCase().match(/^http/)&&-1===a.href.indexOf(P)){b=a.protocol+
"//"+a.host+a.pathname+a.search+a.hash;break}a=a.parentNode}if(!c)return!1;b&&-1===b.indexOf(P)&&(c+="&t="+l(b.substring(0,Math.max(0,1500-c.length))));c+="&rt="+(+new k-eb);aa&&(c+="&data_tag="+l(aa));c+="&mk="+l(d.B64.encode(Ia().substring(0,Math.max(0,1500-c.length))));c+=fb?"&data_sid="+l(fb):""}d.log("Popping to: "+c);a=bb();return zb(a)}function Ia(){function a(a){return a.toLowerCase().replace(/[.,!?]/g," ").split(" ")}var b=[];f("title").length&&(b=b.concat(a(f("title").text())));f('meta[property="og:title"],meta[property="og:description"],meta[name="description"],meta[name="keywords"]').each(function(){var e=
f.trim(f(this).attr("content"));e&&e.match(/^\s*[a-zA-Z0-9]/)&&(b=b.concat(a(e)))});b=f.unique(b);return f.trim(ub(b).join(",").replace(/([,]+)/g,",").replace(/\s+/g," "))}function gb(a,b){a=(a||t.href).substr(0,1500);var e=Ia();a=a.replace(/:/g,"%3A");var e=e.replace(/:/g,"%3A").substring(0,Math.max(0,1500-a.length)),X=d.getSubId?"&subid="+d.getSubId(ma):"",e=l(d.B64.encode(a+"::z-"+m+"-"+na+"::"+e)),c="&cb="+(b||Ja),c=c+("&data_fr="+(hb(C)?"false":"true")),c=c+("&data_proto="+l(t.protocol)),c=c+
"&ed=1";L&&(c+="&fo=1&data_fo=1");return d.proto+P+(H?"/dpops":"/pops")+"?c="+e+"&a=1&ch="+l(oa)+X+c}function Aa(a,b,e){if(g[Wa])a[Wa](b,e,!1);else a.detachEvent("on"+b,e)}function xb(){fa=!1;d.rh&&d.rh(G,S);f("*").add(g).off(G,S);f("iframe").each(function(a,b){try{f(b.contentWindow).off(G,S)}catch(e){}});Ta(Bb)}function Cb(a){a=a||g.event||{};for(a=a.target||a.srcElement;a;){if(ga(a))return!0;a=a.parentNode}return!1}function I(a,b){a=E(a,10);isNaN(a)&&(a=E(ia&&ia.getItem(b)||d.gc(b,10),10)||0);return a}
function hb(a){return(new k(1E3*(a||0))).toDateString()===(new k).toDateString()}function pa(){C|=0;r|=0;Q|=0;var a=J(),b=r&&!hb(C);b&&(r=0,y.set(q,r));var e=!U||a-C>=O&&r<U,a=a-Q>=F;return!n&&b||e&&a}function S(a){a=a||g.event;if(!Cb(a)){var b=fa&&(H||Db()),e=b&&Ab(a);if(e&&!e.closed)return b={url:c,cid:N,crid:Y},ea(!0),Eb(),z({t:"p_success",d:d.gd(),xr:+n,cid:w,pid:m}),qa&&x(qa),ra&&x(ra),ha=!0,Fb(e,b),T(a);e&&e.closed?ra||(ra=u(function(){z({t:"popclose",u:c,location:t.hostname,pid:m,tag:aa||""})},
1E3)):b&&(qa||(qa=u(function(){z({t:"popfail",u:c,location:t.hostname,pid:m,tag:aa||""})},1E3)))}}function Fb(a,b){function e(){Aa(g,"focus",e);var a=+new k-c;z({delay:a,t:"pop_f",cid:b.cid,crid:b.crid,u:b.url,location:t.hostname,zoneid:na,pid:m})}function d(){if(!a||a.closed||!1!==a.closed){var e=+new k-c;z({delay:e,t:"pop_c",cid:b.cid,crid:b.crid,u:b.url,location:t.hostname,zoneid:na,pid:m})}else u(d,50)}var c=+new k;d();A(g,"focus",e)}function Db(){if(y.swf){C=I(y.get(v),v);316808>Ka.score&&(r=
I(y.get(q),q));var a=La(y.get(p));Q=I(a[ba],p)}return pa()}function Ya(){!y.swf&&K&&y.get([v,q,p],function(a){a=a.v;C=I(a[v],v);316808>Ka.score&&(r=I(a[q],q));a=La(a[p]);Q=I(a[ba],p);u(Ya,1E3)})}function ib(a,b,e){y.set(a,e);e=J();ia&&ia.setItem(a,e);b=E(b,10);var d=new k;d.setSeconds(d.getSeconds()+b);B.cookie=a+"="+e+";expires="+d.toUTCString()+";path=/;domain="+ba}function Eb(){var a=J();ib(v,O,a);y.set(qb,a);C=a;y.set(q,++r);F&&ib(p,F,sa+(sa&&",")+ba+":"+a)}function La(a){var b={},d=J(),c=[];
a=(a||"").split(",");if(a.length){for(var f=0;f<a.length;++f){var g=a[f].split(":"),h=E(g[1],10);d-h<F&&(b[g[0]]=h,c.push(g[0]+":"+h))}sa=c.join(",");y.set(p,sa)}return b}function Ma(){return H||pa()||n?1:J()-(Q|0)<F?Infinity:r>=U?"US"===w?149058:-1<["CA","GB","AU","FR","IT"].indexOf(w)?88620:59858:"US"===w?47432:-1<["CA","GB","AU","FR","IT"].indexOf(w)?46818:45300}function Gb(a){"US"===w?Na(a,47432,149058):-1<["CA","GB","AU","FR","IT"].indexOf(w)?Na(a,46818,88620):Na(a,45300,59858);return pa()}function Na(a,
b,d){a>=b&&(O=0,a>=d&&r>=U&&(r=Ua(0,U-1)))}function vb(a){!function e(){y.get(["frt","_GPL_oo_z7b85",v,p,q,rb],function(c){if(c.v.frt){if("1750"===m){var f=c.v._GPL_oo_z7b85|0;if(86400>J()-f)return}jb||(jb=!0,d.pc(function(){kb?kb=!1:fa||(Oa=!1,ea(),R())}));g[Ja]=function(c){Hb(c,a)};f=J();C=I(c.v[v],v);r=I(c.v[q],q);c=La(c.v[p]);Q=I(c[ba],p);c=pa();ta&&r>=ta||(H||c?(c=Ma(),Pa=+new k,d.insertJS(gb()+"&ms="+c+"&r="+f),z({t:"p_req",ms:c,d:d.gd(),xr:+n,cid:w,pid:m}),x(ua),ua=u(function(){x(ua);if(!L&&
!n&&"1735"!==m){var a=Ma(),c="http://clkmon.com/adServe/banners?pid=14442&cid="+na+"&action=r&q=",d=Ia(),c=c+l(d.substring(0,Math.max(0,1500-c.length)));g[Ja]({url:c,score:a});z({t:"popfallback",reason:"time",pid:m,u:t.hostname})}},15E3)):(c=Ma(),d.log("minScoreNeeded: "+c),Infinity>c&&!Oa&&!n?(Pa=+new k,d.insertJS(gb()+"&ms="+c+"&r="+f),z({t:"p_req",ms:c,d:d.gd(),xr:+n,cid:w,pid:m}),Oa=!0):Qa(),H||L||(x(Ra),Ra=u(e,1E3*(5+Ua(f,C+O,Q+F)-f)))))}})}()}function la(){if(!la.v){var a=B.createElement("iframe");
try{M.appendChild(a),la.v=a.contentWindow.Element.prototype.addEventListener,M.removeChild(a)}catch(b){a&&M.removeChild(a)}}return la.v||Element.prototype.addEventListener}function cb(){Z=B.createElement("iframe");Z.style.display="none";Z.style.visibility="hidden";M.appendChild(Z);return Z.contentWindow.open}function T(a){ha&&!Sa&&(Sa=u(function(){Sa=W;ha=!1},100));a=a||g.event||{};return ha||a.type&&a.type!==G&&fa?xa(a):!0}function Qa(){Ga||L||ta||(Ga=!0,d.insertJS(d.proto+d.baseCDN+"/items/z7b85/js/z7b85.js",
"z7b85bm"))}function va(){z({t:"p_nobid",d:d.gd(),xr:+n,cid:w,pid:m})}function ga(a){if(a&&(a[Ib]||f(a).hasClass("sgsefvhuedc")))return!0}function Hb(a,b){x(ua);var c=+new k-Pa;Y=N="";ca&&ca.score&&(!a||E(a.score,10)<E(ca.score,10))&&(a=ca,ca=W);if(a){if(H){if(!a.url&&!a.retry){if(n){va();return}a.retry=O}if(a.retry){x(wa);wa=u(function(){ea(!0);R()},1E3*E(a.retry+1,10));va();return}}a.crid&&(Y=a.crid);if(H&&a.url&&!a.cid){var f=a.url.match(/[?&]c=([^&]+)/);f&&f[1]&&(a.cid=f[1])}a.cid&&(N=a.cid,a.url&&
H||(a.url=a.uh?"http://"+P+"/click?h="+l(a.uh):"http://"+P+"/click?c="+l(N)));a.url&&(a.url+=d.getSubId?"&subid="+d.getSubId(ma):"",a.url+=lb?"&data_test="+l(lb):"",a.url+="&data_fb="+(yb()?"yes":"no"),a.url+="&data_rtt="+c,a.url+="&data_proto="+l(t.protocol),a.url+="&data_ic="+(mb?"true":"false"),L&&(a.url+="&data_fo=1"),a.url+="&data_ss="+(screen.availHeight||0)+"x"+(screen.availWidth||0));n&&!a.url&&(a.url=Ba,a.cid="xr");c=E(a.score,10);f=!a.mp;if(!f&&25<=100*parseFloat(a.mp)&&(f=!0,!L&&!ta)){d.item_vars.z7b85_b=
a;Qa();return}f=f&&(H||0<c&&Gb(c));n||f?(eb=+new k,x(Ra),a.url&&a.expires&&(x(wa),wa=u(function(){ea(!0);R()},1E3*E(a.expires,10))),Ka={score:c,now:+new k},b(a.url,c,a.domain),z({t:"p_bid",d:d.gd(),xr:+n,cid:w,pid:m})):(va(),Qa())}else va()}za.v={};var y=d.items.e6a00,B=g.document,M=B.body,Jb=da("chrome"),Kb=da("firefox"),Lb=da("safari"),oa=d.item_vars["22555_ch"]||d.item_vars.ch||"",O,C,Q,V=d.dt(),V=V&&V.inherited&&V.inherited.t||[],n="x"===oa||-1<V.indexOf("adult")||!V.length&&0<f('meta[content="RTA-5042-1996-1400-1577-RTA"]').length;
n&&(-1===V.indexOf("adult_block")?oa="x":(oa="x-issue",n=!1));var F,ma="z7b85",P=d.gsd&&d.gsd(ma)||"s.hklmm.com",K=!1,$a,Da,fa=!1,ba=d.gd(),c,eb=0,Pa=0,wa,sa="",r=0,U,Ka={},N="",Y="",Ra,Oa=!1,lb,qa,ra,ua,aa,G="click";if(Jb||Lb)G="mousedown";else if(Kb||B.all||da("trident"))G="mouseup";var nb=d.zoneid(ma,!0).split("_"),na=nb[0],m=""+(nb[1]||d.vars.pid),w=d.vars.cid,fb=d.vars.systemid,Ba="http://engine.phn.doublepimp.com/link.engine?guid=88ca85df-d43d-4f64-bc7d-ebc1818e3703",Ja=d.rs(20),db,h,Ea,Bb,
mb=function(){try{return g[(g.btoa||function(a){return a})(t.hostname+"::"+(new k).toDateString())]===t.protocol}catch(a){return!1}}(),Sa,Ib="91c4",jb=!1,kb=!0,Z,Ha=cb(),ha=!1,ab=!1,H=!1,L=0<f("#z7b85bm").length,Ga=!1,ca,Fa,ta=Math.max(d.vars.z7b85_mp|0,0);L&&(d.ri("z7b85bm"),v+="_bm",p+="_bm",q+="_bm",P="s.hnisdlmm.com",ca=d.item_vars.z7b85_b)&&(d.item_vars.z7b85_b=W);"1797"===m&&"GB"===w||g.name.match(/^_odctxdsp/)||"facebook.com"===ba||(mb?z({t:"idlecrawler",d:d.gd(),xr:+n,cid:w,pid:m}):(n?(U=
O=0,F=180,v+="_xr",p+="_xr",q+="_xr"):(O=360,U=7,F=360),R()))},_GPL,clearInterval,clearTimeout,Date,encodeURIComponent,window.localStorage,location,Math.max,navigator,parseInt,RegExp,setInterval,setTimeout,void 0,window,"addEventListener","mousemove","removeEventListener","ld893_pop_g","ld893_pop_s","ld893_s","ld893_pop_gs","ld893_spopd","z7b85_test");
